#name: ci-golang-workflow
#on: [push]
#jobs:
#  check-application:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-go@v2
#        with:
#          go-version: 1.18
#      - run: go test
#      - run: go run math.go

# name: ci-golang-workflow
# on: 
#   pull_request:
#     branches:
#       - develop
# jobs:
#  check-application:
#    runs-on: ubuntu-latest
#    strategy:
#     matrix:
#       go: ['1.17', '1.18']
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-go@v2
#        with:
#          go-version: ${{ matrix.go }}
#      - run: go test ./CI_class
#      - run: go run ./CI_class/math.go

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1

#      - name: Set up docker buildx
#        uses: docker/setup-buildx-action@v1

#      - name: Login to dockerhub
#        uses: docker/login-action@v1
#        with:
#         username: ${{secrets.DOCKERHUB_USERNAME}}
#         password: ${{secrets.DOCKERHUB_TOKEN}}

#      - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v6
#        with:
#          push: false
#          tags: gabrielggs/full-cycle:latest

name: ci-sonarcloud
on:
  pull_request:
    branches:
      - develop

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test ./CI_class -coverprofile=coverage.out